<script>
    document.getElementById("surveyForm").addEventListener("submit", function(event) {
        event.preventDefault(); // Prevent the default form submission

        // Retrieve all input values
        const T = parseFloat(document.getElementById("T").value);
        const A = parseFloat(document.getElementById("A").value);
        const Y = parseFloat(document.getElementById("Y").value);
        const V = parseFloat(document.getElementById("V").value);
        const F = parseFloat(document.getElementById("F").value);
        const W = parseFloat(document.getElementById("W").value);
        const D = parseFloat(document.getElementById("D").value);
        const O = parseFloat(document.getElementById("O").value);
        const R = parseFloat(document.getElementById("R").value);
        const L = parseFloat(document.getElementById("L").value);
        const C = parseFloat(document.getElementById("C").value);
        const Z = parseFloat(document.getElementById("Z").value);
        const X = parseFloat(document.getElementById("X").value);
        const M = parseFloat(document.getElementById("M").value);
        const Q = parseFloat(document.getElementById("Q").value);

        // Calculation example (you can adjust based on your desired formula)
        const result = (T + A + Y + V + F + W + D + O + R + L + C + Z + X + M + Q) / 15;

        // Display the result
        document.getElementById("result").innerHTML = `Your overall job preference score is: ${result.toFixed(2)}`;
    });
</script>
