<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job Survey</title>
    <style>
        label, input, select, button {
            display: block;
            margin-bottom: 10px;
        }

        .result {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Job Preference Survey</h1>

    <form id="surveyForm">
        <h3>Proximity to Jobsite (J)</h3>
        <label for="T">Travel Cost (0 &lt; T &lt; 0.5):</label>
        <input type="number" id="T" min="0" max="0.5" step="0.01" required>

        <label for="A">Accessibility (0 &lt; A &lt; 0.5):</label>
        <input type="number" id="A" min="0" max="0.5" step="0.01" required>

        <h3>Pay (P)</h3>
        <label for="Y">Frequency of Pay (0, 0.1, 0.2, 0.3):</label>
        <select id="Y" required>
            <option value="0">0</option>
            <option value="0.1">0.1</option>
            <option value="0.2">0.2</option>
            <option value="0.3">0.3</option>
        </select>

        <label for="V">Amount of Pay (0 &lt; V &lt; 0.7):</label>
        <input type="number" id="V" min="0" max="0.7" step="0.01" required>

        <h3>Hours (H)</h3>
        <label for="F">Flexibility (0 &lt; F &lt; 0.25):</label>
        <input type="number" id="F" min="0" max="0.25" step="0.01" required>

        <label for="W">Required Hours per Week (0 &lt; W &lt; 0.25):</label>
        <input type="number" id="W" min="0" max="0.25" step="0.01" required>

        <label for="D">Seasonal (0 or 0.25):</label>
        <input type="number" id="D" min="0" max="0.25" step="0.25" required>

        <label for="O">Available Hours per Week (0 &lt; O &lt; 0.25):</label>
        <input type="number" id="O" min="0" max="0.25" step="0.01" required>

        <h3>Skills (S)</h3>
        <label for="R">Required Training (0 or 0.5):</label>
        <input type="number" id="R" min="0" max="0.5" step="0.5" required>

        <label for="L">Time to Learn (0 &lt; L &lt; 0.5):</label>
        <input type="number" id="L" min="0" max="0.5" step="0.01" required>

        <h3>Work Environment (E)</h3>
        <label for="C">Clientele (0 &lt; C &lt; 0.3):</label>
        <input type="number" id="C" min="0" max="0.3" step="0.01" required>

        <label for="Z">Coworkers (0 &lt; Z &lt; 0.4):</label>
        <input type="number" id="Z" min="0" max="0.4" step="0.01" required>

        <label for="X">Cleanliness (0 &lt; X &lt; 0.3):</label>
        <input type="number" id="X" min="0" max="0.3" step="0.01" required>

        <h3>Additional Factors (M + Q)</h3>
        <label for="M">M:</label>
        <input type="number" id="M" min="0" max="1" step="0.01" required>

        <label for="Q">Q:</label>
        <input type="number" id="Q" min="0" max="1" step="0.01" required>

        <button type="submit">Calculate Result</button>
    </form>

    <div class="result" id="result">
        <!-- Result will be displayed here -->
    </div>
</body>
</html>
